{{- if .Values.localSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exec-ud-daas-etl-service.fullname" . }}-local-secrets
type: Opaque
data:
  DB_USER: {{ default "" .Values.localSecrets.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ default "" .Values.localSecrets.DB_PASSWORD | b64enc | quote }}
  DB_HOST: {{ default "" .Values.localSecrets.DB_HOST | b64enc | quote }}
{{- end }}