{{- if .Values.secretProvider }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "exec-ud-daas-etl-service.fullname" . }}-azure-key-vault
spec:
  provider: "azure"
  parameters:
    keyvaultName: {{ or .Values.secretProvider.keyVault .Values.global.keyVault | quote }}
    tenantId: {{ or .Values.secretProvider.tenantId .Values.global.tenantId | quote }}
    objects:  |
      array:
        {{- range .Values.secretProvider.secrets }}
        - |
          objectName: {{ quote .vaultName }}
          objectType: {{ quote .type }}
          {{- if .version }}
          objectVersion: {{ quote .version }}
          {{- end }}
        {{- end }}
        {{- range .Values.secretProvider.environmentSecrets }}
        - |
          objectName: {{ quote .vaultName }}
          objectType: {{ quote .type }}
          {{- if .version }}
          objectVersion: {{ quote .version }}
          {{- end }}
        {{- end }}
        {{- range .Values.global.secrets }}
        - |
          objectName: {{ quote .vaultName }}
          objectType: {{ quote .type }}
          {{- if .version }}
          objectVersion: {{ quote .version }}
          {{- end }}
        {{- end }}
        {{- range .Values.global.environmentSecrets }}
        - |
          objectName: {{ quote .vaultName }}
          objectType: {{ quote .type }}
          {{- if .version }}
          objectVersion: {{ quote .version }}
          {{- end }}
        {{- end }}
  secretObjects:
  - secretName: {{ include "exec-ud-daas-etl-service.fullname" . }}-secrets
    type: Opaque
    data:
    {{- range .Values.secretProvider.secrets }}
    - key: {{ quote .k8sName }}
      objectName: {{ quote .vaultName }}
    {{- end }}
    {{- range .Values.secretProvider.environmentSecrets }}
    - key: {{ quote .k8sName }}
      objectName: {{ quote .vaultName }}
    {{- end }}
    {{- range .Values.global.secrets }}
    - key: {{ quote .k8sName }}
      objectName: {{ quote .vaultName }}
    {{- end }}
    {{- range .Values.global.environmentSecrets }}
    - key: {{ quote .k8sName }}
      objectName: {{ quote .vaultName }}
    {{- end }}
{{- end }}