apiVersion: v1
kind: Service
metadata:
  name: {{ include "exec-ud-daas-etl-service.fullname" . }}
  labels:
    {{- include "exec-ud-daas-etl-service.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "exec-ud-daas-etl-service.selectorLabels" . | nindent 4 }}
