name: Performance Tests (PR)

on:
  workflow_dispatch: # allow manual triggering
  pull_request:
    paths-ignore:
      - '.github'
      - '**.md'


env:
  ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.EXEC_ECOM_ARTIFACTORY_USERNAME }}
  ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.EXEC_ECOM_ARTIFACTORY_PASSWORD }}

jobs:
  precheck:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      performance_tests_exist: ${{ steps.performance_test_check.outputs.performance_tests_exist }}

    steps:
      - uses: actions/checkout@v2

      - id: performance_test_check
        name: Check if performance tests exist
        run: |
          echo ::set-output name=performance_tests_exist::$(test -f performance/build.gradle && echo "true")

  perftests:
    runs-on: ubuntu-latest
    needs: precheck
    timeout-minutes: 60
    if: needs.precheck.outputs.performance_tests_exist == 'true'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Bzt
        id: installBzt
        run: pip install bzt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Jar
        id: build
        run: ./gradlew bootJar

      - name: Run Perf Tests
        id: runPerfTests
        run: |
          ./gradlew bztInit
          ./gradlew bztAll

      - name: Kill Compose Stack
        if: ${{ always() }}
        id: killComposeStack
        run: ./gradlew composeDown
